### ISSUE TITLE
how to get card_cryptogram_packet value

### ISSUE THREAD

**Issue by devmildfire** [drforse/aiocloudpayments#1]
Sorry if i am misunderstanding something, but i have trouble getting the value for card_cryptogram_packet argument. As i understand it, the value is generated by the script, which is provided by cloudpayments platform itself. The script is written in JavaScript and can be executed on a site as a usual JavaScript code. But how does one get the card_cryptogram_packet  value in the code of a bot, written in python? Is there a way to get the card_cryptogram_packet  value without the usual script? Can you please explain this in more detail?

Also, is there an example of a bot, which uses this library for the cloudpayments integration? 

Thanks for your time and consideration.

**Comment by drforse** [comment]
Hi. I don't think that cloudpayments api considers a possibility of using it anywhere but a website. But I am not fully sure about it and I'm not an official representative of CloudPayments, if I were you I would ask CloudPayments support about it and then, after getting an answer from them you may use the library according to the how they tell you about using api.

I am not aware about any opensource bot which uses this library. But I can send you more detailed examples if you tell me what do you want to do exactly. 

And also, when I was implementing payments in a bot, I made a web-page with cloudpayments widget which was opened in a bot. I think that is the only way cuz that's the only way CloudPayments can assure users the payment is secure and you can't steal card info.

**Comment by drforse** [comment]
If you read article about CloudPayments api integration scenarios, there you won't found a scenario for payments without a web-page: https://developers.cloudpayments.ru/#platezhi-cherez-api-cloudpayments

**Comment by drforse** [comment]
I don't think there is any payments provider that allows you to make payments without using web page/android app/telegram internal payments system, because... Well, it's not safe
